### ISSUE TITLE
Digital Ocean have their own Snap

### ISSUE THREAD

**Issue by joedborg** [snapcrafters/doctl#1]
https://github.com/digitalocean/doctl/blob/master/snap/snapcraft.yaml

Just a discussion point @popey, @flexiondotorg, et.al.  Just wondering if DO are ready for the reins to be passed over to them?

**Comment by evandandrea** [comment]
Oh wow! Would you be willing to reach out to them, @joedborg?

**Comment by Ads20000** [comment]
[This bug](https://github.com/digitalocean/doctl/issues/136) is an existing discussion about snaps of doctl.

**Comment by popey** [comment]
DO now own this snap, so closing this bug. I will also delete this repo, as it's no longer required.
